version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:30"
  open-pull-requests-limit: 1
  assignees:
    - baurtock
  reviewers:
    - baurtock
  groups:
    all:
      patterns:
        - "*"